Fix dockerfile name

diff --git a/ci/build_helper_docker b/ci/build_helper_docker
--- a/ci/build_helper_docker
+++ b/ci/build_helper_docker
@@ -9,12 +9,12 @@ source "${SCRIPTPATH}/docker_buildx_commands"
 # shellcheck source=ci/.colors
 source "${SCRIPTPATH}/.colors"
 
-experimental=$(_docker_experimental info -f '{{json .ExperimentalBuild}}')
-if [ "${experimental}" = 'false' ]; then
-    echo -e "${RED}Docker experimental mode needs to be enabled for multi-platform build support. Aborting."
-    echo -e "See https://github.com/docker/cli/blob/master/experimental/README.md#use-docker-experimental for more information.${RST}"
-    exit 1
-fi
+#experimental=$(_docker_experimental info -f '{{json .ExperimentalBuild}}')
+#if [ "${experimental}" = 'false' ]; then
+#    echo -e "${RED}Docker experimental mode needs to be enabled for multi-platform build support. Aborting."
+#    echo -e "See https://github.com/docker/cli/blob/master/experimental/README.md#use-docker-experimental for more information.${RST}"
+#    exit 1
+#fi
 
 TARGET_ARCH=$1
 TARGET_FILE=$2
@@ -41,7 +41,7 @@ esac;
 
 if [[ -n "$UBI" ]]; then
     case "$platform_arch" in
-      # If the platform we are building for isn't supported buy the
+      # If the platform we are building for isn't supported by the
       # redhat ubi image exit the script
       "amd64"|"arm64"|"s390x")
         ;;
