no buildx pls

diff --git a/ci/build_helper_docker b/ci/build_helper_docker
--- a/ci/build_helper_docker
+++ b/ci/build_helper_docker
@@ -56,17 +56,26 @@ echo -e "Building helper image for: ${GRN}${platform}${RST}"
 trap cleanup_docker_context_trap ERR SIGINT SIGTERM
 setup_docker_context
 
-echo "------$platform"
 if [[ "$platform" = "linux/amd64" ]]; then
-  echo "------true"
+  IMAGE="gitlab/gitlab-runner-helper-ubi:$TARGET_ARCH-$REVISION"
+  docker build \
+    -t "$IMAGE" \
+    --build-arg ARCH="$TARGET_ARCH" \
+    -f dockerfiles/runner-helper/Dockerfile.OCP \
+    dockerfiles/runner-helper/
+
   TARGET_FILE_UBI=${TARGET_FILE/prebuilt-/prebuilt-ubi-}
-  _docker_buildx build \
-      --platform "${platform}" \
-      --no-cache \
-      --output "type=tar,dest=${TARGET_FILE_UBI}" \
-      --tag "gitlab/gitlab-runner-helper-ubi:$TARGET_ARCH-$REVISION" \
-      -f dockerfiles/runner-helper/Dockerfile.OCP \
-      dockerfiles/runner-helper/ || echo "buildx ubi failed for platform ${platform}"
+  docker image save \
+    -o "$TARGET_FILE_UBI"
+    "$IMAGE"
+
+#  _docker_buildx build \
+#      --platform "${platform}" \
+#      --no-cache \
+#      --output "type=tar,dest=${TARGET_FILE_UBI}" \
+#      --tag "gitlab/gitlab-runner-helper-ubi:$TARGET_ARCH-$REVISION" \
+#      -f dockerfiles/runner-helper/Dockerfile.OCP \
+#      dockerfiles/runner-helper/ || echo "buildx ubi failed for platform ${platform}"
 
   if test -f "$TARGET_FILE_UBI"; then
       xz -f -9 "${TARGET_FILE_UBI}" || echo "couldn't compress ubi ${TARGET_FILE_UBI}"
