buildx no tar

diff --git a/ci/build_helper_docker b/ci/build_helper_docker
--- a/ci/build_helper_docker
+++ b/ci/build_helper_docker
@@ -58,22 +58,20 @@ setup_docker_context
 
 if [[ "$platform" = "linux/amd64" ]]; then
   IMAGE="registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper-ubi:x86_64-${REVISION}"
-  docker build \
-    -t "$IMAGE" \
-    -f dockerfiles/runner-helper/Dockerfile.OCP \
-    dockerfiles/runner-helper/
+#  docker build \
+#    -t "$IMAGE" \
+#    -f dockerfiles/runner-helper/Dockerfile.OCP \
+#    dockerfiles/runner-helper/
 
+  _docker_buildx build \
+      --platform "${platform}" \
+      --no-cache \
+      --tag "$IMAGE" \
+      -f dockerfiles/runner-helper/Dockerfile.OCP \
+      dockerfiles/runner-helper/ || echo "buildx ubi failed for platform ${platform}"
   echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
   docker push "$IMAGE"
   docker logout "${CI_REGISTRY}"
-
-#  _docker_buildx build \
-#      --platform "${platform}" \
-#      --no-cache \
-#      --output "type=tar,dest=${TARGET_FILE_UBI}" \
-#      --tag "gitlab/gitlab-runner-helper-ubi:$TARGET_ARCH-$REVISION" \
-#      -f dockerfiles/runner-helper/Dockerfile.OCP \
-#      dockerfiles/runner-helper/ || echo "buildx ubi failed for platform ${platform}"
 
   if test -f "$TARGET_FILE_UBI"; then
       xz -f -9 "${TARGET_FILE_UBI}" || echo "couldn't compress ubi ${TARGET_FILE_UBI}"
